<?php

declare(strict_types=1);

namespace Aether\AOT;

use Aether\Attributes\Entity;
use Aether\Attributes\Column;

/**
 * Entity Generator — AOT compilation for ORM entities.
 *
 * Scans classes for #[Entity] and properties for #[Column].
 * Generates static hydrators and SQL metadata.
 *
 * @package Aether\AOT
 */
final class EntityGenerator
{
    /**
     * @param array<string, string> $paths Namespace => directory
     * @param string $outputPath
     */
    public function generate(array $paths, string $outputPath): void
    {
        $entities = [];
        foreach ($paths as $namespace => $directory) {
            $classes = $this->discoverClasses($directory, $namespace);
            foreach ($classes as $className) {
                if (!class_exists($className)) continue;
                $ref = new \ReflectionClass($className);
                if (count($ref->getAttributes(Entity::class)) > 0) {
                    $entities[$className] = $this->analyzeEntity($ref);
                }
            }
        }

        $this->writeFile($entities, $outputPath);
    }

    private function analyzeEntity(\ReflectionClass $ref): array
    {
        $attr = $ref->getAttributes(Entity::class)[0]->newInstance();
        $table = $attr->table ?: strtolower($ref->getShortName()) . 's';

        $columns = [];
        foreach ($ref->getProperties() as $prop) {
            $colAttrs = $prop->getAttributes(Column::class);
            if (empty($colAttrs)) continue;
            $col = $colAttrs[0]->newInstance();
            $columns[$prop->getName()] = [
                'name' => $col->name ?: $prop->getName(),
                'type' => $col->type,
                'pk' => $col->primaryKey,
                'auto' => $col->autoIncrement,
            ];
        }

        return [
            'table' => $table,
            'columns' => $columns,
        ];
    }

    private function writeFile(array $entities, string $outputPath): void
    {
        $lines = [];
        $lines[] = "<?php";
        $lines[] = "";
        $lines[] = "declare(strict_types=1);";
        $lines[] = "";
        $lines[] = "/**";
        $lines[] = " * AUTO-GENERATED by Aether AOT Entity Generator.";
        $lines[] = " * Generated: " . date('Y-m-d H:i:s');
        $lines[] = " */";
        $lines[] = "";
        $lines[] = "return [";

        foreach ($entities as $class => $meta) {
            $lines[] = "    '{$class}' => [";
            $lines[] = "        'table' => '{$meta['table']}',";
            $lines[] = "        'columns' => [";
            foreach ($meta['columns'] as $prop => $col) {
                $lines[] = "            '{$prop}' => [";
                $lines[] = "                'name' => '{$col['name']}',";
                $lines[] = "                'type' => '{$col['type']}',";
                $lines[] = "                'pk' => " . ($col['pk'] ? 'true' : 'false') . ",";
                $lines[] = "                'auto' => " . ($col['auto'] ? 'true' : 'false') . ",";
                $lines[] = "            ],";
            }
            $lines[] = "        ],";
            
            // Hydrator closure
            $lines[] = "        'hydrator' => static function (array \$row): \\{$class} {";
            $lines[] = "            \$e = new \\{$class}();";
            foreach ($meta['columns'] as $prop => $col) {
                $type = $col['type'];
                $val = "\$row['{$col['name']}']";
                $cast = match($type) {
                    'int', 'integer' => "(int){$val}",
                    'float', 'double' => "(float){$val}",
                    'bool', 'boolean' => "(bool){$val}",
                    default => "(string){$val}",
                };
                $lines[] = "            if (isset({$val})) { \$e->{$prop} = {$cast}; }";
            }
            $lines[] = "            return \$e;";
            $lines[] = "        },";
            $lines[] = "    ],";
        }

        $lines[] = "];";

        file_put_contents($outputPath, implode("\n", $lines), LOCK_EX);
    }

    private function discoverClasses(string $directory, string $namespace): array
    {
        $classes = [];
        $files = $this->findPhpFiles($directory);
        $baseDir = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        foreach ($files as $file) {
            $relative = substr($file, strlen($baseDir));
            $relative = substr($relative, 0, -4);
            $classes[] = $namespace . '\\' . str_replace(DIRECTORY_SEPARATOR, '\\', $relative);
        }
        return $classes;
    }

    private function findPhpFiles(string $dir): array
    {
        $files = [];
        $items = scandir($dir);
        if ($items === false) return $files;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            $path = $dir . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) $files = array_merge($files, $this->findPhpFiles($path));
            elseif (str_ends_with($item, '.php')) $files[] = $path;
        }
        return $files;
    }
}
