<?php

declare(strict_types=1);

namespace Aether\AOT;

use Aether\Attributes\Listener;

/**
 * Event Generator — AOT compilation for Event Bus.
 *
 * Scans methods for #[Listener] and builds a static dispatch map.
 *
 * @package Aether\AOT
 */
final class EventGenerator
{
    /**
     * @param array<string, string> $paths Namespace => directory
     * @param string $outputPath
     */
    public function generate(array $paths, string $outputPath): void
    {
        $map = [];
        foreach ($paths as $namespace => $directory) {
            $classes = $this->discoverClasses($directory, $namespace);
            foreach ($classes as $className) {
                if (!class_exists($className)) continue;
                $ref = new \ReflectionClass($className);
                foreach ($ref->getMethods() as $method) {
                    $attrs = $method->getAttributes(Listener::class);
                    foreach ($attrs as $attr) {
                        $instance = $attr->newInstance();
                        $map[$instance->event][] = [
                            'class' => $className,
                            'method' => $method->getName(),
                            'priority' => $instance->priority,
                        ];
                    }
                }
            }
        }

        // Sort by priority
        foreach ($map as $event => &$listeners) {
            usort($listeners, fn($a, $b) => $b['priority'] <=> $a['priority']);
        }

        $this->writeFile($map, $outputPath);
    }

    private function writeFile(array $map, string $outputPath): void
    {
        $lines = [];
        $lines[] = "<?php";
        $lines[] = "";
        $lines[] = "declare(strict_types=1);";
        $lines[] = "";
        $lines[] = "use Aether\\Container\\Container;";
        $lines[] = "";
        $lines[] = "/**";
        $lines[] = " * AUTO-GENERATED by Aether AOT Event Generator.";
        $lines[] = " * Generated: " . date('Y-m-d H:i:s');
        $lines[] = " */";
        $lines[] = "";
        $lines[] = "return [";

        foreach ($map as $event => $listeners) {
            $lines[] = "    '{$event}' => [";
            foreach ($listeners as $l) {
                $lines[] = "        static function (object \$event, Container \$c) {";
                $lines[] = "            return \$c->resolve('{$l['class']}')->{$l['method']}(\$event);";
                $lines[] = "        },";
            }
            $lines[] = "    ],";
        }

        $lines[] = "];";

        file_put_contents($outputPath, implode("\n", $lines), LOCK_EX);
    }

    private function discoverClasses(string $directory, string $namespace): array
    {
        $classes = [];
        $files = $this->findPhpFiles($directory);
        $baseDir = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        foreach ($files as $file) {
            $relative = substr($file, strlen($baseDir));
            $relative = substr($relative, 0, -4);
            $classes[] = $namespace . '\\' . str_replace(DIRECTORY_SEPARATOR, '\\', $relative);
        }
        return $classes;
    }

    private function findPhpFiles(string $dir): array
    {
        $files = [];
        $items = scandir($dir);
        if ($items === false) return $files;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            $path = $dir . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) $files = array_merge($files, $this->findPhpFiles($path));
            elseif (str_ends_with($item, '.php')) $files[] = $path;
        }
        return $files;
    }
}
