<?php

declare(strict_types=1);

namespace Aether\AOT;

use Aether\Attributes\Dto;
use Aether\Attributes\Validate;

/**
 * Validation Generator — AOT compilation for DTO validation.
 *
 * Scans classes for #[Dto] and properties for #[Validate] attributes.
 * Generates flat PHP conditional statements to replace runtime reflection
 * and dynamic rule parsing.
 *
 * @package Aether\AOT
 */
final class ValidationGenerator
{
    /**
     * @param array<string, string> $paths Namespace => directory
     * @param string $outputPath
     */
    public function generate(array $paths, string $outputPath): void
    {
        $dtos = [];
        foreach ($paths as $namespace => $directory) {
            $classes = $this->discoverClasses($directory, $namespace);
            foreach ($classes as $className) {
                if (!class_exists($className)) continue;
                $ref = new \ReflectionClass($className);
                if (count($ref->getAttributes(Dto::class)) > 0) {
                    $dtos[$className] = $this->analyzeDto($ref);
                }
            }
        }

        $this->writeFile($dtos, $outputPath);
    }

    private function analyzeDto(\ReflectionClass $ref): array
    {
        $rules = [];
        foreach ($ref->getProperties() as $prop) {
            $propRules = [];
            $attrs = $prop->getAttributes(Validate::class);
            foreach ($attrs as $attr) {
                $instance = $attr->newInstance();
                $propRules[] = [
                    'rule' => $instance->rule,
                    'message' => $instance->message,
                    'params' => $instance->params,
                ];
            }
            if (!empty($propRules)) {
                $rules[$prop->getName()] = $propRules;
            }
        }
        return $rules;
    }

    private function writeFile(array $dtos, string $outputPath): void
    {
        $lines = [];
        $lines[] = "<?php";
        $lines[] = "";
        $lines[] = "declare(strict_types=1);";
        $lines[] = "";
        $lines[] = "use Aether\\Validation\\ValidationResult;";
        $lines[] = "";
        $lines[] = "/**";
        $lines[] = " * AUTO-GENERATED by Aether AOT Validation Generator.";
        $lines[] = " * Generated: " . date('Y-m-d H:i:s');
        $lines[] = " */";
        $lines[] = "";
        $lines[] = "return [";

        foreach ($dtos as $className => $props) {
            $lines[] = "    '{$className}' => static function (array \$data): ValidationResult {";
            $lines[] = "        \$errors = [];";
            $lines[] = "        \$validated = [];";
            
            foreach ($props as $propName => $rules) {
                $lines[] = "        \$val = \$data['{$propName}'] ?? null;";
                foreach ($rules as $rule) {
                    $condition = $this->generateCondition($rule['rule'], $rule['params'], '$val', $propName);
                    $message = $rule['message'] !== '' ? $rule['message'] : "Validation failed for {$propName} ({$rule['rule']})";
                    $lines[] = "        if ({$condition}) { \$errors['{$propName}'] = '{$message}'; }";
                }
                $lines[] = "        if (!isset(\$errors['{$propName}'])) { \$validated['{$propName}'] = \$val; }";
            }

            $lines[] = "        return new ValidationResult(empty(\$errors), \$validated, \$errors);";
            $lines[] = "    },";
        }

        $lines[] = "];";

        file_put_contents($outputPath, implode("\n", $lines), LOCK_EX);
    }

    private function generateCondition(string $rule, array $params, string $var, string $field): string
    {
        return match ($rule) {
            'email' => "filter_var({$var}, FILTER_VALIDATE_EMAIL) === false",
            'url' => "filter_var({$var}, FILTER_VALIDATE_URL) === false",
            'min' => "is_string({$var}) && strlen({$var}) < " . (int)($params['length'] ?? 0),
            'max' => "is_string({$var}) && strlen({$var}) > " . (int)($params['length'] ?? PHP_INT_MAX),
            'numeric' => "!is_numeric({$var})",
            'integer' => "filter_var({$var}, FILTER_VALIDATE_INT) === false",
            'required' => "{$var} === null || {$var} === ''",
            default => "false",
        };
    }

    private function discoverClasses(string $directory, string $namespace): array
    {
        $classes = [];
        $files = $this->findPhpFiles($directory);
        $baseDir = rtrim($directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR;

        foreach ($files as $file) {
            $relative = substr($file, strlen($baseDir));
            $relative = substr($relative, 0, -4);
            $classes[] = $namespace . '\\' . str_replace(DIRECTORY_SEPARATOR, '\\', $relative);
        }
        return $classes;
    }

    private function findPhpFiles(string $dir): array
    {
        $files = [];
        $items = scandir($dir);
        if ($items === false) return $files;
        foreach ($items as $item) {
            if ($item === '.' || $item === '..') continue;
            $path = $dir . DIRECTORY_SEPARATOR . $item;
            if (is_dir($path)) $files = array_merge($files, $this->findPhpFiles($path));
            elseif (str_ends_with($item, '.php')) $files[] = $path;
        }
        return $files;
    }
}
